---
title: "Homework 2"
output: github_document
---

# Setup

```{r, setup}
library(tidyverse)
library(readxl)
```

## Problem 1

Read in and clean up the Mr. Trashwheel dataset
```{r}
trashwheel_df = 
  read_xlsx("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "Mr. Trash Wheel",
      range = cell_cols("A:N")) %>% 
      janitor::clean_names() %>% 
      drop_na(dumpster) %>% 
      mutate(
        sports_balls = round(sports_balls),
        sports_balls = as.integer(sports_balls))
```

Read in precipitation excel spreadsheet for the 2018 and 2017 data.  

```{r}
precip_2018 = 
  read_xlsx("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "2018 Precipitation",
      skip = 1) %>% 
      janitor::clean_names() %>% 
      drop_na(month) %>% 
      mutate(year = 2018) %>% 
      relocate(year)

precip_2017 = 
  read_xlsx("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "2017 Precipitation",
      skip = 1) %>% 
      janitor::clean_names() %>% 
      drop_na(month) %>% 
      mutate(year = 2017) %>% 
      relocate(year)
```

### Now bind 2017 and 2018 precipitation data.

```{r}
  precip_df = bind_rows(precip_2017, precip_2018)
```

### Create a month number to month name tibble.

```{r}
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )
```

### Include a month name 

```{r}
left_join(precip_df, month_df, by = "month")
```

